

#ifndef TCPMESSENGERPROTOCOL_H_
#define TCPMESSENGERPROTOCOL_H_


#define MSNGR_PORT 5555
#define VERIFYFILENAME "users.txt"

#define ERRORNAME -1
#define MESSAGE 0
#define REGISTERCOMMAND 1
#define LOGINCOMMAND 2
#define LIST 3
#define AUTOMATCH 4
#define REQUEST 5
#define ACCEPT_FROM_PEER 6
#define REJECT_FROM_PEER 7
#define DISCONNECTFROMPEER 8
#define DISCONNECT 9
#define UNKNOWNCOMMAND 10
#define CONNECT_TO_PEER 11
#define GAMEOVER 12



#endif /* TCPMESSENGERPROTOCOL_H_ */
